-- Add missing columns to images table
ALTER TABLE public.images 
ADD COLUMN IF NOT EXISTS notes TEXT,
ADD COLUMN IF NOT EXISTS visit_id UUID REFERENCES visits(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS tooth_number INTEGER,
ADD COLUMN IF NOT EXISTS surface VARCHAR(50),
ADD COLUMN IF NOT EXISTS disease_id VARCHAR(100),
ADD COLUMN IF NOT EXISTS treatment_id VARCHAR(100),
ADD COLUMN IF NOT EXISTS dentist_id UUID REFERENCES users(id) ON DELETE SET NULL,
ADD COLUMN IF NOT EXISTS dentist_name VARCHAR(255);
