-- Disable RLS on all tables
ALTER TABLE IF EXISTS public.clinics DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.users DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.roles DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.permissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.role_permissions DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.patients DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.appointments DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.follow_ups DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.platform_audit_logs DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.image_records DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.clinical_notes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.ambulances DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.emergency_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.blood_inventory DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.blood_requests DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.facilities DISABLE ROW LEVEL SECURITY;

-- Grant access to anon role for all tables
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO anon;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO anon;
GRANT ALL PRIVILEGES ON ALL ROUTINES IN SCHEMA public TO anon;
